### PR TITLE
Remove duplication in microgrammars.md and fix line number

### PR DESCRIPTION
**Pull request by janekdb**

### CODE REVIEW

**Comment by janekdb** [comment]
I didn't make a change to this,

```
'§[a-zA-Z0-9_\\.]+§'
```

because I don't have a way to test the change and don't know TypeScript flavour regex, but in regexes dot loses it's metacharacter meaning in square brackets so this could be,

```
'§[a-zA-Z0-9_.]+§'
```

**Comment by janekdb** [comment]
Also with this example I am guessing that this would cause the edit to be skipped with not project fail message as there would be no match in the path expression,

`<modelVersion>!!!!****TODO:Update the version number when we have time*****!!!!</modelVersion>`

**Comment by kipz** [comment]
LGTM

**Comment by ddgenome** [comment]
Thanks, I'll merge this in and we can open issues for the other two things you mention.

**Pull request merged**
