### PR TITLE
User guide editor

### PR DESCRIPTION
**Pull request by Lawouach**
Hopefully matching the style and structure of the generator.

### CODE REVIEW

**Comment by ddgenome** [comment]
While the generator guide started with a standard project, I think editors, like handlers, probably belong in a separate project. What do you think?

**Comment by Lawouach** [comment]
How do you mean? Not relying on mkdocs?

**Comment by ddgenome** [comment]
We can talk about it tomorrow. More concretely for this PR, I don't think starting with an empty rug project is informative. Just start with the editor and testing in place and go from there.

**Comment by Lawouach** [comment]
This will be taken care of in PR #109

**Pull request closed without merging**
