### PR TITLE
First draft of event handler documentation. Remove executors. #96

### PR DESCRIPTION
**Pull request by kipz**

### CODE REVIEW

**Comment by Lawouach** [comment]
LGTM from an introduction perspective. However, we have tried not to tie pages too much together. I wonder if we could benefit from a little more explanation here, even though it would look very much a copy/paste from the command handler section. 

I like the simple example! We probably should have done that in command handlers too.

**Comment by kipz** [comment]
Why aren't we tying things together? There's a big risk of errors if we are duplicating things, and hyperlinks are good for linking :)

**Comment by Lawouach** [comment]
The difficulty is that you must always make sure that, when changing one side, you ensure it doesn't break what the other side is saying. Standalone pages are more verbose but avoid that coupling.

I'm happy with either to be fair, we could perhaps revisit this next week? :)

**Comment by kipz** [comment]
I think we should get this information updated, and I'll work on creating a common section on handlers to be included in each handler type (using a new plugin).

**Comment by Lawouach** [comment]
I think that could work indeed.

**Pull request merged**
